language: rust
os: osx
rust:
- nightly
- beta
- 1.4.0
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "uuid rustc-serialize time unix_socket serde_json chrono openssl bit-vec security-framework"
